### ISSUE TITLE
request trained weight file

### ISSUE THREAD

**Issue by SqLiu67** [AndyCao1125/EOLO#2]
Hello author
We are very interested in your article and code. However, we've noticed some discrepancies in the results during our attempts to reproduce them.  If it is convenient for you, could you please provide the trained weight file for our reference? Thank you!

**Comment by SageCao1125** [comment]
Thank you for your attention. The pretrained weight of EOLO in under-exposure scene is now provided in this repository. It's worth noting that our model was trained on a synthetic event dataset, and the results for other real-world scenarios may vary.
